# Generated by Django 5.0.2 on 2024-03-20 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('teenplay_title', models.TextField()),
                ('video_path', models.ImageField(upload_to='teenplay_video/%Y/%m/%d')),
                ('thumbnail_path', models.ImageField(upload_to='teenplay_thumbnail/%Y/%m/%d')),
                ('status', models.BooleanField(default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
            ],
            options={
                'db_table': 'tbl_teenplay',
            },
        ),
        migrations.CreateModel(
            name='TeenPlayLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('teenplay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teenplay.teenplay')),
            ],
            options={
                'db_table': 'tbl_teenplay_like',
            },
        ),
    ]
