# Generated by Django 5.0.2 on 2024-03-20 16:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('teenplay_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('club_name', models.TextField()),
                ('club_intro', models.TextField()),
                ('club_info', models.TextField(null=True)),
                ('club_profile_path', models.ImageField(upload_to='club/%Y/%m/%d')),
                ('club_banner_path', models.ImageField(upload_to='club/%Y/%m/%d')),
                ('status', models.BooleanField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alarm_status', models.BooleanField(default=1)),
                ('status', models.SmallIntegerField(choices=[(-1, '가입대기'), (0, '탈퇴'), (1, '가입중')], default=-1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club_member',
            },
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_title', models.TextField()),
                ('notice_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
            ],
            options={
                'db_table': 'tbl_club_notice',
            },
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
                ('image_path', models.ImageField(upload_to='club_post/%Y/%m/%d')),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teenplay_server.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.club')),
            ],
            options={
                'db_table': 'tbl_club_post',
            },
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubPostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.TextField()),
                ('status', models.BooleanField(default=1)),
                ('club_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.clubpost')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_club_post_reply',
            },
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
